### ISSUE TITLE
Jar upload to bintray failed 

### ISSUE THREAD

**Issue by Pascal-Verdier** [tango-controls/JTango#76]
**mvn release:perform**  works during a while.
But during upload to bintray, a **curl** error occurs.
In **bintray** we can find several new files but no **jar** file !

Any idea ?

```
[INFO] 806/806 B   
[INFO]             
[INFO] Uploaded: https://api.bintray.com/maven/tango-controls/jtango/JTango/;publish=1/org/tango-controls/JTango/maven-metadata.xml (806 B at 0.3 KB/sec)
[INFO] [INFO] 
[INFO] [INFO] --- exec-maven-plugin:1.5.0:exec (deploy-jar) @ JTango ---
[INFO]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[INFO]                                  Dload  Upload   Total   Spent    Left  Speed
[INFO] 
[INFO]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 160.103.208.60...
[INFO] * TCP_NODELAY set
[INFO] * Connected to (nil) (160.103.208.60) port 3128 (#0)
[INFO] * ALPN, offering h2
[INFO] * ALPN, offering http/1.1
[INFO] * Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
[INFO] * successfully set certificate verify locations:
[INFO] *   CAfile: none
[INFO]   CApath: /etc/ssl/certs
[INFO] * TLSv1.2 (OUT), TLS header, Certificate Status (22):
[INFO] } [5 bytes data]
[INFO] * TLSv1.2 (OUT), TLS handshake, Client hello (1):
[INFO] } [512 bytes data]
[INFO] * error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
[INFO] * Curl_http_done: called premature == 0
[INFO] 
[INFO]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[INFO] * Closing connection 0
[INFO] curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
[INFO] [ERROR] Command execution failed.
[INFO] org.apache.commons.exec.ExecuteException: Process exited with an error: 35 (Exit value: 35)
[INFO]  at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
[INFO]  at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
[INFO]  at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:764)
[INFO]  at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:711)
[INFO]  at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:289)
[INFO]  at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[INFO]  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
[INFO]  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[INFO]  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[INFO]  at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[INFO]  at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[INFO]  at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[INFO]  at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[INFO]  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
[INFO]  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
[INFO]  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
[INFO]  at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
[INFO]  at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[INFO]  at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO]  at java.lang.reflect.Method.invoke(Method.java:498)
[INFO]  at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[INFO]  at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[INFO]  at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[INFO]  at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Reactor Summary:
[INFO] [INFO] 
[INFO] [INFO] JTangoParent ....................................... SUCCESS [ 12.896 s]
[INFO] [INFO] JavaTangoIDL ....................................... SUCCESS [ 29.066 s]
[INFO] [INFO] Java common ........................................ SUCCESS [ 25.703 s]
[INFO] [INFO] Java DAO ........................................... SUCCESS [05:25 min]
[INFO] [INFO] JTango Client Lang ................................. SUCCESS [ 23.015 s]
[INFO] [INFO] JTango Server ...................................... SUCCESS [ 45.191 s]
[INFO] [INFO] JTango full assembly ............................... FAILURE [ 13.468 s]
[INFO] [INFO] JTango ............................................. SKIPPED
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] BUILD FAILURE
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Total time: 07:55 min
[INFO] [INFO] Finished at: 2019-08-06T11:29:25+02:00
[INFO] [INFO] Final Memory: 60M/1075M
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Total time: 07:55 min
[INFO] [INFO] Finished at: 2019-08-06T11:29:25+02:00
[INFO] [INFO] Final Memory: 60M/1075M
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (deploy-jar) on project JTango: Command execution failed. Process exited with an error: 35 (Exit value: 35) -> [Help 1]
[INFO] [ERROR] 
[INFO] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[INFO] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[INFO] [ERROR] 
[INFO] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[INFO] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[INFO] [ERROR] 
[INFO] [ERROR] After correcting the problems, you can resume the build with the command
[INFO] [ERROR]   mvn <goals> -rf :JTango
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] JTangoParent ....................................... SKIPPED
[INFO] JavaTangoIDL ....................................... SKIPPED
[INFO] Java common ........................................ SKIPPED
[INFO] Java DAO ........................................... SKIPPED
[INFO] JTango Client Lang ................................. SKIPPED
[INFO] JTango Server ...................................... SKIPPED
[INFO] JTango full assembly ............................... SKIPPED
[INFO] JTango ............................................. FAILURE [08:03 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by bourtemb** [comment]
I uploaded JTango-9.5.15.jar manually using curl. I had no issue with my account.

This what I did:

```
git clone git@github.com:tango-controls/JTango.git
cd JTango
# Move JTango version back to 9.5.15 (I could have used the tag too)
git reset --hard HEAD~1
mvn package
cd assembly/target
curl -T JTango-9.5.15.jar -ubourtemb:<MyBintrayAPIKey> https://api.bintray.com/content/tango-controls/generic/JTango-9-LTS/9.5.15/JTango-9.5.15.jar
```

Then I went on bintray (I got the beta version) who asked me whether I wanted to publish the unpublished files. I said yes.
The fat jar for 9.5.15 seems to be available now (https://dl.bintray.com/tango-controls/generic/JTango-9.5.15.jar)
Please tell me if I forgot something (are there other files to upload?) or if I did something wrong.
I didn't synchronize with Maven Central.

**Comment by Pascal-Verdier** [comment]
Fixed in my environment with:
**unset HTTPS_PROXY**
